export const JOB_STATUS = {
  FABRIC_ISSUED: 'FABRIC_ISSUED',
  SENT_TO_CUTTING: 'SENT_TO_CUTTING',
  CUTTING_COMPLETED: 'CUTTING_COMPLETED',
  LINE_ASSIGNED: 'LINE_ASSIGNED',
  LINE_IN_PROGRESS: 'LINE_IN_PROGRESS',
  LINE_COMPLETED: 'LINE_COMPLETED',
  WASHING_OUT: 'WASHING_OUT',
  AFTER_WASH_RECEIVED: 'AFTER_WASH_RECEIVED',
  PACKING_COMPLETED: 'PACKING_COMPLETED',
  WAREHOUSE_RECEIVED: 'WAREHOUSE_RECEIVED',
};

const ALLOWED_TRANSITIONS = {
  [JOB_STATUS.FABRIC_ISSUED]: [JOB_STATUS.SENT_TO_CUTTING],
  [JOB_STATUS.SENT_TO_CUTTING]: [JOB_STATUS.CUTTING_COMPLETED],
  [JOB_STATUS.CUTTING_COMPLETED]: [JOB_STATUS.LINE_ASSIGNED],
  [JOB_STATUS.LINE_ASSIGNED]: [JOB_STATUS.LINE_IN_PROGRESS, JOB_STATUS.LINE_COMPLETED, JOB_STATUS.WASHING_OUT],
  [JOB_STATUS.LINE_IN_PROGRESS]: [JOB_STATUS.LINE_COMPLETED],
  [JOB_STATUS.LINE_COMPLETED]: [JOB_STATUS.WASHING_OUT],
  [JOB_STATUS.WASHING_OUT]: [JOB_STATUS.WASHING_OUT, JOB_STATUS.AFTER_WASH_RECEIVED],
  [JOB_STATUS.AFTER_WASH_RECEIVED]: [JOB_STATUS.PACKING_COMPLETED],
  [JOB_STATUS.PACKING_COMPLETED]: [JOB_STATUS.WAREHOUSE_RECEIVED],
  [JOB_STATUS.WAREHOUSE_RECEIVED]: [],
};

export function assertTransition(current, next) {
  const allowed = ALLOWED_TRANSITIONS[current];
  if (!allowed) throw new Error(`Unknown status: ${current}`);
  if (!allowed.includes(next)) {
    throw new Error(
      `Invalid transition: ${current} → ${next}. Allowed: [${allowed.join(', ')}]`
    );
  }
}

export const STATUS_LABELS = {
  FABRIC_ISSUED: 'Fabric Issued',
  SENT_TO_CUTTING: 'Sent to Cutting',
  CUTTING_COMPLETED: 'Cutting Done',
  LINE_ASSIGNED: 'Line Assigned',
  LINE_IN_PROGRESS: 'In Production',
  LINE_COMPLETED: 'Production Done',
  WASHING_OUT: 'At Washing',
  AFTER_WASH_RECEIVED: 'Wash Received',
  PACKING_COMPLETED: 'Packing Done',
  WAREHOUSE_RECEIVED: 'In Warehouse',
};
